if patched_font_in_use; then
	# TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="⮂"
	# TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="⮃"
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="\~"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="\~"
	# TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="⮀"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="\~"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="⮁"
else
	# TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

# TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'235'}
TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'234'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'255'}

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}

if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		"hostname 234 0" \
		"tmux_session_info 234 37" \
		# "pwd 89 211" \
	  "vcs_branch 234 37" \
		"vcs_compare 234 37" \
		"vcs_staged 234 37" \
		"vcs_modified 234 37" \
		"vcs_others 234 37" \
		# "lan_ip 24 255 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}" \
	)
fi

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		"mail_count 234 37" \
		"now_playing 234 136" \
		# "wan_ip 24 255" \
		# "cpu 240 136" \
		# "load 237 167" \
		#"tmux_mem_cpu_load 234 136" \
		# "ifstat 234 37" \
		# "ifstat_sys 234 37" \
		"weather 234 255" \
		"xkb_layout 125 117" \
		"battery 234 37" \
		# "date_day 234 136" \
		"date_full 234 136 " \
		"time 234 136" \
	)
fi
